micronaut:
  server:
    context-path: /photobook-demo
  application:
    name: micronaut-photobook
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      openapi-explorer:
        paths: classpath:META-INF/swagger/views/openapi-explorer
        mapping: /openapi-explorer/**
      assets:
        paths: classpath:static/home/
        mapping: /home/**

mongodb:
  uri: mongodb://localhost:27017/photobook_demo