micronaut:
  server:
    context-path: /photobook-demo
    http-version: 2.0
  application:
    name: micronaut-photobook
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      openapi-explorer:
        paths: classpath:META-INF/swagger/views/openapi-explorer
        mapping: /openapi-explorer/**
      assets:
        paths: classpath:static/home/
        mapping: /home/**
  caches:
    images:
      charset: 'UTF-8'

mongodb:
  uri: ${MONGODB_URL:`mongodb://localhost:27017/photobook_demo`}