FROM debian:bookworm-slim

WORKDIR /app

# Copy the native binary from the build stage
COPY target/micronaut-photobook /app/micronaut-photobook

# Run the application
ENTRYPOINT [ "sh", "-c", "/app/micronaut-photobook ${JAVA_OPTS_APPEND}"]